# Generated by Django 3.2.6 on 2021-08-08 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Emplyee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eid', models.CharField(max_length=22)),
                ('ename', models.CharField(max_length=100)),
                ('emailid', models.EmailField(max_length=254)),
                ('econtact', models.CharField(max_length=40)),
            ],
        ),
    ]
